# We have to pass `sources`, so minimize the number of files that are scanned
sources:
  - ../templates
templates:
  - ../templates/AppSecrets.stencil
output:
  ../../Adequate/Application
args:
  service_region: ${SERVICE_REGION}
  platform_application_arn: ${PLATFORM_APPLICATION_ARN}
  topic_arn: ${TOPIC_ARN}
  logger_app_id: ${LOGGER_APP_ID}
  logger_app_secret: ${LOGGER_APP_SECRET}
  logger_encryption_key: ${LOGGER_ENCRYPTION_KEY}
